addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.17")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.0.0")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly" % "0.14.10")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.0")
